
version: 2.1
orbs:
  node: circleci/node@1.1
jobs:
  
  second_job:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "This is second Job without sleep"
  first_job:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Echo with sleep"
      - run: sleep 10
      - run: echo "My pipeline id is << pipeline.id >> and my git branch is << pipeline.git.branch >>"
  print_envs:
    environment:
      MY_NAME: "Pius pipeline"
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: echo "${MY_NAME} other env ${CIRCLE_WORKFLOW_ID:0:2} "
      - run: echo "Circle job is ${CIRCLE_JOB} and pull request username is ${CIRCLE_PR_USERNAME}"
  create_file_to_share:
    docker:
      - image: circleci/node:13.8.0
    steps:
     - checkout
     - run: mkdir /tmp/workspace
     - run: echo "value to store in file" > /tmp/workspace/output.txt

     - persist_to_workspace: # this saves a file to workspace for sharing
        root: /tmp/workspace #required for persist workspace. It can be an absolute path or one relative to pwd
        paths: #paths relative to the workspace  root. Must not be root itself
          - file/share/output.txt #directory /tmp/workspace/file/share now exiists
          - share      # directory /tmp/workspace/share now exists.
  print_out_workspace:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: echo "This is attach to workspace"
      - attach_workspace:
          at: /tmp/workspace
      - run: cat /tmp/workspace/output.txt

workflows: # workflow is used to coordinate job execution. Some jobs may only get executed after others
  version: 2.1
  workflow_name: #use any convenient name for the workflow
    jobs: #list the jobs this workflow should run
      - second_job
      - first_job:
          requires:
            - second_job
      - print_envs
      - print_out_workspace:
          requires:
            - create_file_to_share
      - create_file_to_share
