
version: 2.1
orbs:
  node: circleci/node@1.1
jobs:
  
  second_job:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "This is second Job without sleep"
  first_job:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Echo with sleep"
      - run: sleep 10
workflows: # workflow is used to coordinate job execution. Some jobs may only get executed after others
  version: 2.1
  workflow_name: #use any convenient name for the workflow
    jobs: #list the jobs this workflow should run
      - second_job
      - first_job:
          requires:
            - second_job

