# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run
 print_hello:
    docker: #using the docker executor
      -image: circleci/ruby:2.4.1 #docker image to use
    #Steps are list of commands to be executed in the docker executor
    steps:
      - checkout # tells the CI_CD to pull code from github
      - run: echo "hello from first Job"
      - run: sleep 25
      #- node/with-cache:
      #    steps:
      #      - run: npm install
      #- run: npm run test