Resources:
    Ec2Instance:
      Type: 'AWS::EC2::Instance'
      Properties:
        SecurityGroups:
          - !Ref InstanceSecurityGroup
        KeyName: CI_CD_Key
        ImageId: 'ami-0a63f96e85105c6d3'
    InstanceSecurityGroup:
      Type: 'AWS::EC2::SecurityGroup'
      Properties:
        GroupDescription: Enable SSH access via port 22
        SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: '22'
            ToPort: '22'
            CidrIp: 0.0.0.0/0